### ISSUE TITLE
Adjust ErrorAlert

### ISSUE THREAD

**Issue by novadeveloper14** [selsa-inube/crediboard#166]
Ajuste el componente ErrorAlert para que el ícono de cerrar esté siempre a la derecha y no adjunto al texto, además el ícono de advertencia está muy adjunto al texto y debe estar en los extremos y el texto debe estar centrado verticalmente.

![image](https://github.com/user-attachments/assets/ba9df0ec-6f21-44dc-99bf-ad8c401df314)

**Comment by carin91** [comment]
This issue was addressed in at/cb-224-issue
